<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-10-14T22:34:43 IST" name="Default suite" finished-at="2020-10-14T22:38:27 IST" duration-ms="223831">
    <groups>
    </groups>
    <test started-at="2020-10-14T22:34:43 IST" name="Default test" finished-at="2020-10-14T22:38:27 IST" duration-ms="223831">
      <class name="Com.Qa.LoginTest.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:Com.Qa.LoginTest.LoginTest@21b2e768]" started-at="2020-10-14T22:34:43 IST" name="setup" finished-at="2020-10-14T22:34:57 IST" duration-ms="13476" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Login_Page_Test()[pri:1, instance:Com.Qa.LoginTest.LoginTest@21b2e768]" started-at="2020-10-14T22:34:57 IST" name="Login_Page_Test" finished-at="2020-10-14T22:35:29 IST" duration-ms="32022" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_Page_Test -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Com.Qa.LoginTest.LoginTest@21b2e768]" started-at="2020-10-14T22:35:29 IST" name="teardown" finished-at="2020-10-14T22:35:31 IST" duration-ms="2039" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:Com.Qa.LoginTest.LoginTest@21b2e768]" started-at="2020-10-14T22:35:31 IST" name="setup" finished-at="2020-10-14T22:35:41 IST" duration-ms="10141" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Login_Page_Negative_Test()[pri:2, instance:Com.Qa.LoginTest.LoginTest@21b2e768]" started-at="2020-10-14T22:35:41 IST" name="Login_Page_Negative_Test" finished-at="2020-10-14T22:36:06 IST" duration-ms="24999" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Projects · Dashboard · GitLab] but found [Sign in to GitHub · GitHub]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Projects · Dashboard · GitLab] but found [Sign in to GitHub · GitHub]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at Com.Qa.LoginTest.LoginTest.Login_Page_Negative_Test(LoginTest.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_Page_Negative_Test -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Com.Qa.LoginTest.LoginTest@21b2e768]" started-at="2020-10-14T22:36:06 IST" name="teardown" finished-at="2020-10-14T22:36:14 IST" duration-ms="8028" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:Com.Qa.LoginTest.LoginTest@21b2e768]" started-at="2020-10-14T22:36:14 IST" name="setup" finished-at="2020-10-14T22:36:27 IST" duration-ms="13000" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Login_Page_Email_ID_Test()[pri:3, instance:Com.Qa.LoginTest.LoginTest@21b2e768]" started-at="2020-10-14T22:36:27 IST" name="Login_Page_Email_ID_Test" finished-at="2020-10-14T22:36:45 IST" duration-ms="17877" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_Page_Email_ID_Test -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Com.Qa.LoginTest.LoginTest@21b2e768]" started-at="2020-10-14T22:36:45 IST" name="teardown" finished-at="2020-10-14T22:36:51 IST" duration-ms="5952" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:Com.Qa.LoginTest.LoginTest@21b2e768]" started-at="2020-10-14T22:36:51 IST" name="setup" finished-at="2020-10-14T22:37:31 IST" duration-ms="40090" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Login_Page_Email_ID_Negative_Test()[pri:4, instance:Com.Qa.LoginTest.LoginTest@21b2e768]" started-at="2020-10-14T22:37:31 IST" name="Login_Page_Email_ID_Negative_Test" finished-at="2020-10-14T22:38:08 IST" duration-ms="36993" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Projects · Dashboard · GitLab] but found [Sign in · GitLab]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Projects · Dashboard · GitLab] but found [Sign in · GitLab]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at Com.Qa.LoginTest.LoginTest.Login_Page_Email_ID_Negative_Test(LoginTest.java:88)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_Page_Email_ID_Negative_Test -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Com.Qa.LoginTest.LoginTest@21b2e768]" started-at="2020-10-14T22:38:08 IST" name="teardown" finished-at="2020-10-14T22:38:27 IST" duration-ms="18793" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Com.Qa.LoginTest.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
